[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:product]
command=node /app/apps/services/product/dist/index.js
environment=PORT="4001",INVENTORY_SERVICE_URL="http://localhost:4003"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:inventory]
command=node /app/apps/services/inventory/dist/index.js
environment=PORT="4003"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:order]
command=node /app/apps/services/order/dist/index.js
environment=PORT="4002",INVENTORY_SERVICE_URL="http://localhost:4003",CART_SERVICE_URL="http://localhost:4004",PRODUCT_SERVICE_URL="http://localhost:4001"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:cart]
command=node /app/apps/services/cart/dist/index.js
environment=PORT="4004",PRODUCT_SERVICE_URL="http://localhost:4001"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:api]
command=node /app/apps/api/dist/index.js
environment=PORT="8000",PRODUCT_SERVICE_URL="http://localhost:4001",INVENTORY_SERVICE_URL="http://localhost:4003",ORDER_SERVICE_URL="http://localhost:4002",CART_SERVICE_URL="http://localhost:4004"
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
